


student = {
    'first_name': 'John',
    'last_name': 'Doe',
    'gender': 'Male',
    'age': 25,
    'marital_status': 'Single',
    'skills': ['Python', 'Data Analysis', 'Machine Learning', 'Public Speaking', 'Project Management'],
    'country': 'USA',
    'city': 'New York',
    'address': '123 Main St, New York, NY 10001'
}


values_list = list(student.values())


print(f"The values of the student dictionary are: {values_list}")
